import Pkg;
Pkg.add("POMDPs")
Pkg.add("QuickPOMDPs")
Pkg.add("POMDPModelTools")
Pkg.add("BeliefUpdaters")
Pkg.add("Parameters")
Pkg.add("POMDPPolicies")
Pkg.add("Random")
Pkg.add("Distributions")
Pkg.add("POMDPTools")
# Pkg.add("QMDP")
# Pkg.add("SARSOP")
# Pkg.add("NativeSARSOP")
Pkg.add("FIB")
Pkg.add("HDF5")
